### PR TITLE
fix: update version order when get model version list

### PR DESCRIPTION
**Pull request by Phelan164**
Because

- we would like to return the list of model versions in order

This commit

- return ordered model version list
- add integration test
- cohere style for docker-compose and Makefile
- close instill-ai/vdp#87

Note: this PR tried to resolve the [issue](https://github.com/instill-ai/vdp/issues/87) but have another [issue](https://github.com/instill-ai/model-backend/issues/37)

### CODE REVIEW

**Comment by xiaofei-du** [comment]
When I run the integration test
```
TEST_FOLDER_ABS_PATH=${PWD} ./k6 run tests/integration-tests/model-backend-rest.js 
```

1st time: 100% pass

multiple time: report errors
```bash
█ Model Backend API: Load model online

       ✓ POST /models (multipart) cls response Status
       ✓ POST /models (multipart) cvtask cls response Name
       ✓ POST /models (multipart) cvtask cls response FullName
       ✓ POST /models (multipart) cvtask cls response CVTask
       ✓ POST /models (multipart) cvtask cls response Versions
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 online cvtask cls response Status
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 online cvtask cls response Name
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 online cvtask cls response FullName
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 online cvtask cls response CVTask
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 online cvtask cls response Versions
       ✗ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 online cvtask cls response Version 1 Status
        ↳  0% — ✓ 0 / ✗ 1
       ✗ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 online cvtask cls response Version 2 Status
        ↳  0% — ✓ 0 / ✗ 1
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 online cvtask cls response Status
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 online cvtask cls response Name
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 online cvtask cls response FullName
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 online cvtask cls response CVTask
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 online cvtask cls response Versions
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 online cvtask cls response Version 1 Status
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 online cvtask cls response Version 2 Status
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 offline cvtask cls response Status
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 offline cvtask cls response Name
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 offline cvtask cls response FullName
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 offline cvtask cls response CVTask
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 offline cvtask cls response Versions
       ✗ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 offline cvtask cls response Version 1 Status
        ↳  0% — ✓ 0 / ✗ 1
       ✗ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 offline cvtask cls response Version 2 Status
        ↳  0% — ✓ 0 / ✗ 1
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 offline cvtask cls response Status
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 offline cvtask cls response Name
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 offline cvtask cls response FullName
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 offline cvtask cls response CVTask
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 offline cvtask cls response Versions
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 offline cvtask cls response Version 1 Status
       ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 offline cvtask cls response Version 2 Status
       ✓ DELETE clean up response Status

 █ Model Backend API: Update model version description

       ✓ POST /models (multipart) cls response Status
       ✓ POST /models (multipart) cvtask cls response Name
       ✓ POST /models (multipart) cvtask cls response FullName
       ✓ POST /models (multipart) cvtask cls response CVTask
       ✓ POST /models (multipart) cvtask cls response Versions
       ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/1 cvtask cls response Status
       ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/1 cvtask cls response Name
       ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/1 cvtask cls response FullName
       ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/1 cvtask cls response CVTask
       ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/1 cvtask cls response Versions
       ✗ PATCH /models (multipart) cvtask cls response Version 1 Description
        ↳  0% — ✓ 0 / ✗ 1
       ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/2 cvtask cls response Status
       ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/2 cvtask cls response Name
       ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/2 cvtask cls response FullName
       ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/2 cvtask cls response CVTask
       ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/2 cvtask cls response Versions
       ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/2 cvtask cls response Version 1 Description
       ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/2 cvtask cls response Version 2 Description
       ✓ DELETE clean up response Status
```

**Review by xiaofei-du — CHANGES_REQUESTED** [review]
Please check the above test error comment.

Also, since now `model-backend` has tests, can we use Makefile for the integration tests and unit tests?

**Comment by xiaofei-du** [comment]
> When I run the integration test
> 
> ```
> TEST_FOLDER_ABS_PATH=${PWD} ./k6 run tests/integration-tests/model-backend-rest.js 
> ```
> 
> 1st time: 100% pass
> 
> multiple time: report errors
> 
> ```shell
> █ Model Backend API: Load model online
> 
>        ✓ POST /models (multipart) cls response Status
>        ✓ POST /models (multipart) cvtask cls response Name
>        ✓ POST /models (multipart) cvtask cls response FullName
>        ✓ POST /models (multipart) cvtask cls response CVTask
>        ✓ POST /models (multipart) cvtask cls response Versions
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 online cvtask cls response Status
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 online cvtask cls response Name
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 online cvtask cls response FullName
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 online cvtask cls response CVTask
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 online cvtask cls response Versions
>        ✗ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 online cvtask cls response Version 1 Status
>         ↳  0% — ✓ 0 / ✗ 1
>        ✗ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 online cvtask cls response Version 2 Status
>         ↳  0% — ✓ 0 / ✗ 1
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 online cvtask cls response Status
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 online cvtask cls response Name
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 online cvtask cls response FullName
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 online cvtask cls response CVTask
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 online cvtask cls response Versions
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 online cvtask cls response Version 1 Status
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 online cvtask cls response Version 2 Status
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 offline cvtask cls response Status
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 offline cvtask cls response Name
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 offline cvtask cls response FullName
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 offline cvtask cls response CVTask
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 offline cvtask cls response Versions
>        ✗ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 offline cvtask cls response Version 1 Status
>         ↳  0% — ✓ 0 / ✗ 1
>        ✗ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/1 offline cvtask cls response Version 2 Status
>         ↳  0% — ✓ 0 / ✗ 1
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 offline cvtask cls response Status
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 offline cvtask cls response Name
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 offline cvtask cls response FullName
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 offline cvtask cls response CVTask
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 offline cvtask cls response Versions
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 offline cvtask cls response Version 1 Status
>        ✓ PATCH http://127.0.0.1:8080/models/lvxwfpkggj/versions/2 offline cvtask cls response Version 2 Status
>        ✓ DELETE clean up response Status
> 
>  █ Model Backend API: Update model version description
> 
>        ✓ POST /models (multipart) cls response Status
>        ✓ POST /models (multipart) cvtask cls response Name
>        ✓ POST /models (multipart) cvtask cls response FullName
>        ✓ POST /models (multipart) cvtask cls response CVTask
>        ✓ POST /models (multipart) cvtask cls response Versions
>        ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/1 cvtask cls response Status
>        ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/1 cvtask cls response Name
>        ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/1 cvtask cls response FullName
>        ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/1 cvtask cls response CVTask
>        ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/1 cvtask cls response Versions
>        ✗ PATCH /models (multipart) cvtask cls response Version 1 Description
>         ↳  0% — ✓ 0 / ✗ 1
>        ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/2 cvtask cls response Status
>        ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/2 cvtask cls response Name
>        ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/2 cvtask cls response FullName
>        ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/2 cvtask cls response CVTask
>        ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/2 cvtask cls response Versions
>        ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/2 cvtask cls response Version 1 Description
>        ✓ PATCH http://127.0.0.1:8080/models/xynfntxaxt/versions/2 cvtask cls response Version 2 Description
>        ✓ DELETE clean up response Status
> ```

This is because I tested with an old image. Need to do `docker-compose build` before testing. With the new image, it won't produce the errors caused by wrongly ordered versions.

**Comment by Phelan164** [comment]
@xiaofei-du I also added Makefile for easier running test with `make all; make test`

**Pull request merged**
