### PR TITLE
fix: correct version when making inference

### PR DESCRIPTION
**Pull request by Phelan164**
Because

- versions mismatch between model package (ensemble by preprocessing -> inference -> post-processing) and triton model repository

This commit

- fix Triton model version when making inference

### CODE REVIEW

**Review by pinglin — APPROVED** [review]
LGTM

**Comment by bochengyang** [comment]
Close https://github.com/instill-ai/vdp/issues/76

**Comment by bochengyang** [comment]
close https://github.com/instill-ai/vdp/issues/76

**Comment by xiaofei-du** [comment]
close instill-ai/vdp#76

**Pull request merged**
