### PR TITLE
chore: adopt public/private APIs for model service

### PR DESCRIPTION
**Pull request by heiruwu**
Because

- adopt the updated protobuf public/private APIs

This commit

- update integration-test proto files
- update model service to adopt public/private APIs
- add gRPC operation test cases

### CODE REVIEW

**Comment by Phelan164** [comment]
@heiruwu please commit the go.sum and go.mod file also

**Comment by Phelan164** [comment]
@heiruwu I tried to test but missing controller.proto in integration-test/proto

**Comment by heiruwu** [comment]
>

**Review by Phelan164 — APPROVED** [review]
LGTM

**Pull request merged**
